-- Inserción de Datos Iniciales de Prueba
-- OT_ID se autogenera con la secuencia SEQ_OT (formato OT-YYYY-NNNNNN)

INSERT INTO OT (CLIENTE_ID, PATENTE, DESCRIPCION, TOTAL)
VALUES ('CLI-001', 'XXYY11', 'Mantención 10k', 62000);

INSERT INTO OT_ITEM (OT_ID, CONCEPTO, CANTIDAD, PRECIO_UNIT)
SELECT OT_ID, 'MO-HH', 2, 25000 FROM OT WHERE CLIENTE_ID = 'CLI-001' AND PATENTE = 'XXYY11';

INSERT INTO OT_ITEM (OT_ID, CONCEPTO, CANTIDAD, PRECIO_UNIT)
SELECT OT_ID, 'FILTRO-ACEITE', 1, 12000 FROM OT WHERE CLIENTE_ID = 'CLI-001' AND PATENTE = 'XXYY11';

INSERT INTO OT_EVENT (OT_ID, EVENT_TYPE, PAYLOAD_JSON)
SELECT OT_ID, 'OtCreada', '{"eventType":"OtCreada","otId":"' || OT_ID || '","total":62000}'
FROM OT WHERE CLIENTE_ID = 'CLI-001' AND PATENTE = 'XXYY11';

INSERT INTO NOTIFY_LOG (OT_ID, CLIENTE_ID, CANAL, PAYLOAD_JSON)
SELECT OT_ID, 'CLI-001', 'email', '{"type":"NotificarClienteOtCreada","otId":"' || OT_ID || '"}'
FROM OT WHERE CLIENTE_ID = 'CLI-001' AND PATENTE = 'XXYY11';

INSERT INTO OT (CLIENTE_ID, PATENTE, DESCRIPCION, TOTAL)
VALUES ('CLI-002', 'BBCC22', 'Cambio pastillas freno', 80000);

INSERT INTO OT_ITEM (OT_ID, CONCEPTO, CANTIDAD, PRECIO_UNIT)
SELECT OT_ID, 'PASTILLA-FRENO-DEL', 1, 55000 FROM OT WHERE CLIENTE_ID = 'CLI-002' AND PATENTE = 'BBCC22';

INSERT INTO OT_ITEM (OT_ID, CONCEPTO, CANTIDAD, PRECIO_UNIT)
SELECT OT_ID, 'MO-HH', 1, 25000 FROM OT WHERE CLIENTE_ID = 'CLI-002' AND PATENTE = 'BBCC22';