-- Creación de Tablas adaptadas para H2 Database

CREATE TABLE IF NOT EXISTS OT (
  OT_ID        VARCHAR(24)   PRIMARY KEY,
  CLIENTE_ID   VARCHAR(20)   NOT NULL,
  PATENTE      VARCHAR(10)   NOT NULL,
  DESCRIPCION  VARCHAR(200),
  TOTAL        DECIMAL(12,0) DEFAULT 0 CHECK (TOTAL >= 0),
  CREATED_AT   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT   TIMESTAMP
);

CREATE TABLE IF NOT EXISTS OT_ITEM (
  ITEM_ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
  OT_ID        VARCHAR(24)   NOT NULL,
  CONCEPTO     VARCHAR(40)   NOT NULL,
  CANTIDAD     DECIMAL(10,2) NOT NULL CHECK (CANTIDAD > 0),
  PRECIO_UNIT  DECIMAL(12,0) NOT NULL CHECK (PRECIO_UNIT >= 0),
  SUBTOTAL     DECIMAL(12,0) AS (ROUND(CANTIDAD * PRECIO_UNIT)),
  CREATED_AT   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT FK_OT_ITEM__OT FOREIGN KEY (OT_ID) REFERENCES OT(OT_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS OT_EVENT (
  EVENT_ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
  OT_ID        VARCHAR(24),
  EVENT_TYPE   VARCHAR(40)   NOT NULL,
  PAYLOAD_JSON CLOB          NOT NULL,
  CREATED_AT   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS NOTIFY_LOG (
  LOG_ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
  OT_ID        VARCHAR(24),
  CLIENTE_ID   VARCHAR(20),
  CANAL        VARCHAR(20)   CHECK (CANAL IN ('email','sms','push')),
  PAYLOAD_JSON CLOB          NOT NULL,
  CREATED_AT   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Vista Resumen
CREATE OR REPLACE VIEW V_OT_RESUMEN AS
SELECT
  o.OT_ID,
  o.CLIENTE_ID,
  o.PATENTE,
  o.DESCRIPCION,
  o.TOTAL,
  o.CREATED_AT,
  COUNT(i.ITEM_ID) AS N_ITEMS,
  SUM(i.SUBTOTAL)  AS SUBTOTAL_CALC
FROM OT o
LEFT JOIN OT_ITEM i ON i.OT_ID = o.OT_ID
GROUP BY o.OT_ID, o.CLIENTE_ID, o.PATENTE, o.DESCRIPCION, o.TOTAL, o.CREATED_AT;